import { auth } from '../lib/firebase';
import { getRuntimeEnv } from '../lib/runtimeConfig';

export type CommercialDashboard = { records: Array<Record<string, unknown>>; kpis: { terminales_vendidas: number; comercios_unicos: number; terminales_activadas: number; terminales_pendientes: number; porcentaje_activacion: number | null; gpv: number; transacciones: number }; by_supervisor: Array<{ name: string; ventas: number; gpv: number; transacciones: number }>; by_ejecutivo: Array<{ name: string; ventas: number; gpv: number; transacciones: number }>; by_month: Array<{ name: string; ventas: number; gpv: number; transacciones: number }>; by_week: Array<{ name: string; ventas: number; gpv: number; transacciones: number }>; postventa: Array<{ name: string; ventas: number }>; entel_pending: boolean };
export type CommercialSheet = { name: string; headers: string[]; rows: Record<string, unknown>[]; formulas: string[]; row_count: number };
export type CommercialImport = { campaign: 'Culqi' | 'Entel'; file: { name: string; mime: string; content_base64: string; sha256: string }; sheets: CommercialSheet[]; cutoff_date?: string };
const API = getRuntimeEnv('VITE_API_BASE_URL') || (import.meta.env.PROD ? '' : 'http://localhost:8080');
const request = async <T>(path: string, options: RequestInit = {}, moduleContext = 'comercial:dashboard') => { const token = await auth?.currentUser?.getIdToken(); if (!token) throw new Error('Sesión no disponible.'); const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, 'X-Module-Context': moduleContext, ...options.headers } }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.message || 'No se pudo procesar Gestión Comercial.'); return payload as T; };
export const getCommercialDashboard = (filters: Record<string, string | number | undefined>) => { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value !== undefined && value !== '').map(([name, value]) => [name, String(value)])); return request<CommercialDashboard>(`/api/comercial/dashboard${query.size ? `?${query}` : ''}`); };
export const inspectCommercialImport = (input: CommercialImport) => request<any>('/api/comercial/inspect', { method: 'POST', body: JSON.stringify(input) }, 'comercial:datos');
export const saveCommercialImport = (input: CommercialImport) => request<any>('/api/comercial/imports', { method: 'POST', body: JSON.stringify(input) }, 'comercial:datos');
