import React, { useEffect, useMemo, useRef, useState } from 'react';
import * as XLSX from 'xlsx';
import { AlertTriangle, BarChart3, CheckCircle2, Download, FileSpreadsheet, Filter, Handshake, LineChart as LineIcon, Save, Upload, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { User } from '../types';
import { getCommercialDashboard, inspectCommercialImport, saveCommercialImport, type CommercialDashboard, type CommercialImport, type CommercialSheet } from '../services/commercialService';

interface Props { currentUser: User; initialView?: 'dashboard' | 'ventas' | 'postventa' | 'datos'; }
const empty: CommercialDashboard = { records: [], kpis: { terminales_vendidas: 0, comercios_unicos: 0, terminales_activadas: 0, terminales_pendientes: 0, porcentaje_activacion: null, gpv: 0, transacciones: 0 }, by_supervisor: [], by_ejecutivo: [], by_month: [], by_week: [], postventa: [], entel_pending: true };
const toBase64 = async (file: File) => { const bytes = new Uint8Array(await file.arrayBuffer()); let value = ''; for (let index = 0; index < bytes.length; index += 0x8000) value += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(value); };
const digest = async (file: File) => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', await file.arrayBuffer()))).map((item) => item.toString(16).padStart(2, '0')).join('');
const readSheets = async (file: File): Promise<CommercialSheet[]> => { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array', cellFormula: true, cellDates: true, raw: true }); return workbook.SheetNames.map((name) => { const sheet = workbook.Sheets[name]; const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: null, raw: true }); const headers = (XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, range: 0, defval: '' })[0] || []).map(String); const formulas = Object.values(sheet).filter((cell): cell is XLSX.CellObject => Boolean(cell && typeof cell === 'object' && 'f' in cell && cell.f)).map((cell) => String(cell.f)); return { name, headers, rows, formulas, row_count: rows.length }; }); };
const money = (value: number) => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN', maximumFractionDigits: 0 }).format(value || 0);
const percent = (value: number | null) => value === null ? 'Sin datos' : `${value.toFixed(2)}%`;

export default function GestionComercial({ currentUser, initialView = 'dashboard' }: Props) {
  const [view, setView] = useState(initialView); const [dashboard, setDashboard] = useState(empty); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [campaign, setCampaign] = useState(''); const [year, setYear] = useState(''); const [month, setMonth] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [supervisor, setSupervisor] = useState(''); const [executive, setExecutive] = useState('');
  const [showImport, setShowImport] = useState(false); const [importCampaign, setImportCampaign] = useState<'Culqi' | 'Entel'>('Culqi'); const [pending, setPending] = useState<CommercialImport | null>(null); const [analysis, setAnalysis] = useState<any>(null); const [importing, setImporting] = useState(false); const input = useRef<HTMLInputElement>(null);
  const writable = currentUser.rol === 'Administrador' || (currentUser.module_access?.includes('comercial:datos') && !currentUser.module_view_only?.includes('comercial:datos'));
  const load = async () => { setLoading(true); try { setDashboard(await getCommercialDashboard({ campaign, year, month, from, to, supervisor, executive })); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar Gestión Comercial.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [campaign, year, month, from, to, supervisor, executive]);
  useEffect(() => { setView(initialView); }, [initialView]);
  const supervisors = useMemo(() => dashboard.by_supervisor.map((item) => item.name).filter((name) => name !== 'Sin dato'), [dashboard]); const executives = useMemo(() => dashboard.by_ejecutivo.map((item) => item.name).filter((name) => name !== 'Sin dato'), [dashboard]);
  const stage = async (file?: File) => { if (!file) return; setError(''); setAnalysis(null); try { const sheets = await readSheets(file); const payload: CommercialImport = { campaign: importCampaign, file: { name: file.name, mime: file.type || 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', content_base64: await toBase64(file), sha256: await digest(file) }, sheets }; setPending(payload); setAnalysis(await inspectCommercialImport(payload)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo analizar el archivo.'); } };
  const confirm = async () => { if (!pending) return; setImporting(true); try { await saveCommercialImport(pending); setShowImport(false); setPending(null); setAnalysis(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar la carga.'); } finally { setImporting(false); } };
  const exportRecords = () => { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(dashboard.records), 'Detalle comercial'); XLSX.writeFile(workbook, 'gestion-comercial.xlsx'); };
  const hasCulqi = dashboard.records.some((record) => record.campaign === 'Culqi');
  return <div className="space-y-5 animate-in fade-in duration-300">
    <div className="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Gestión Comercial</p><h2 className="text-xl font-black text-slate-900">Dashboard Comercial</h2></div><div className="flex gap-2">{writable && <button onClick={() => setShowImport(true)} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white"><Upload className="h-4 w-4" />Cargar reporte</button>}<button onClick={exportRecords} disabled={!dashboard.records.length} className="inline-flex items-center gap-2 rounded-lg border border-emerald-200 bg-white px-3 py-2 text-xs font-bold text-emerald-700 disabled:opacity-50"><Download className="h-4 w-4" />Exportar</button></div></div>
    {error && <div className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-xs font-semibold text-rose-800">{error}</div>}
    <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center gap-2 text-sm font-black text-slate-800"><Filter className="h-4 w-4 text-violet-600" />Filtros globales</div><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-7"><Select label="Campaña" value={campaign} setValue={setCampaign} values={['', 'Culqi', 'Entel']} /><Input label="Año" type="number" value={year} setValue={setYear} /><Select label="Mes" value={month} setValue={setMonth} values={['', ...Array.from({ length: 12 }, (_, index) => String(index + 1))]} /><Input label="Desde" type="date" value={from} setValue={setFrom} /><Input label="Hasta" type="date" value={to} setValue={setTo} /><Select label="Supervisor" value={supervisor} setValue={setSupervisor} values={['', ...supervisors]} /><Select label="Ejecutivo" value={executive} setValue={setExecutive} values={['', ...executives]} /></div></div>
    <div className="flex border-b border-slate-200 gap-5"><Tab active={view === 'dashboard'} onClick={() => setView('dashboard')} label="Resumen" /><Tab active={view === 'ventas'} onClick={() => setView('ventas')} label="Ventas" /><Tab active={view === 'postventa'} onClick={() => setView('postventa')} label="Postventa" /><Tab active={view === 'datos'} onClick={() => setView('datos')} label="Gestión de Datos" /></div>
    {campaign === 'Entel' && dashboard.entel_pending && <Empty text="Pendiente de integración del reporte" />}
    {!loading && !dashboard.records.length && campaign !== 'Entel' && <Empty text="Sin datos comerciales validados. Carga un reporte para iniciar el análisis." />}
    {(view === 'dashboard' || view === 'ventas') && hasCulqi && <><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-6"><Kpi title="Terminales vendidas" value={String(dashboard.kpis.terminales_vendidas)} /><Kpi title="Comercios únicos" value={String(dashboard.kpis.comercios_unicos)} /><Kpi title="Terminales activadas" value={String(dashboard.kpis.terminales_activadas)} /><Kpi title="Pendientes" value={String(dashboard.kpis.terminales_pendientes)} /><Kpi title="Activación" value={percent(dashboard.kpis.porcentaje_activacion)} /><Kpi title="GPV" value={money(dashboard.kpis.gpv)} /></div><div className="grid gap-4 xl:grid-cols-2"><Panel title="Activación por mes"><CommercialChart data={dashboard.by_month} line /></Panel><Panel title="Ventas por supervisor"><CommercialChart data={dashboard.by_supervisor} /></Panel>{view === 'ventas' && <><Panel title="Productividad por ejecutivo"><Table rows={dashboard.by_ejecutivo.map((item) => [item.name, String(item.ventas), money(item.gpv), String(item.transacciones)])} headers={['Ejecutivo', 'Ventas', 'GPV', 'Transacciones']} /></Panel><Panel title="Evolución semanal"><CommercialChart data={dashboard.by_week} line /></Panel></>}</div></>}
    {view === 'postventa' && hasCulqi && <div className="grid gap-4 xl:grid-cols-2"><Panel title="Pareto de postventa"><CommercialChart data={dashboard.postventa} /></Panel><Panel title="Detalle operativo"><Table rows={dashboard.records.filter((record) => record.campaign === 'Culqi').map((record) => [String(record.terminal_id || 'Sin dato'), String(record.merchant_id || 'Sin dato'), String(record.postventa || 'Pendiente de validación'), record.gpv == null ? 'Sin datos' : money(Number(record.gpv)), record.transactions == null ? 'Sin datos' : String(record.transactions)])} headers={['Terminal', 'Comercio', 'Situación', 'GPV', 'Transacciones']} /></Panel></div>}
    {view === 'datos' && <Panel title="Registros comerciales"><Table rows={dashboard.records.map((record) => [String(record.sale_date || ''), String(record.campaign || ''), String(record.terminal_id || ''), String(record.merchant_id || ''), String(record.supervisor || ''), String(record.executive || '')])} headers={['Fecha', 'Campaña', 'Terminal', 'Comercio', 'Supervisor', 'Ejecutivo']} /></Panel>}
    {showImport && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-5 shadow-xl"><div className="flex items-start justify-between"><div><h3 className="text-lg font-black text-slate-900">Cargar reporte comercial</h3><p className="text-xs text-slate-500">El archivo se inspecciona antes de consolidar datos.</p></div><button title="Cerrar" onClick={() => { setShowImport(false); setPending(null); setAnalysis(null); }}><X className="h-5 w-5 text-slate-500" /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Select label="Campaña" value={importCampaign} setValue={(value) => setImportCampaign(value as 'Culqi' | 'Entel')} values={['Culqi', 'Entel']} /><label className="text-[10px] font-black uppercase text-slate-500">Archivo Excel<button onClick={() => input.current?.click()} className="mt-1 flex w-full items-center justify-center gap-2 rounded-lg border border-dashed border-violet-300 p-3 text-xs font-bold text-violet-700"><FileSpreadsheet className="h-4 w-4" />Seleccionar archivo</button><input ref={input} type="file" accept=".xlsx,.xls" className="hidden" onChange={(event) => void stage(event.target.files?.[0])} /></label></div>{analysis && <div className="mt-4 space-y-3"><div className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-4"><Kpi title="Leídos" value={String(analysis.records.length + analysis.observed.length)} /><Kpi title="Válidos" value={String(analysis.records.length)} /><Kpi title="Duplicados" value={String(analysis.duplicates)} /><Kpi title="Observados" value={String(analysis.observed.length)} /></div><div className="rounded-lg border border-slate-200 p-3 text-xs text-slate-600"><p className="font-bold text-slate-800">Hojas inspeccionadas: {analysis.inspection.sheets.map((sheet: any) => sheet.name).join(', ')}</p>{analysis.inspection.expected_sheets_missing.length > 0 && <p className="mt-1 text-amber-700">Hojas esperadas no encontradas: {analysis.inspection.expected_sheets_missing.join(', ')}. Los indicadores se consolidarán solo con registros verificables.</p>}{analysis.inspection.external_formula_references.length > 0 && <p className="mt-1 text-amber-700">Hay fórmulas con referencias externas: se marcan como no verificables.</p>}</div><button disabled={importing || !analysis.records.length} onClick={() => void confirm()} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />{importing ? 'Guardando...' : 'Confirmar y guardar'}</button></div>}</div></div>}
  </div>;
}
const Tab = ({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) => <button onClick={onClick} className={`border-b-2 px-1 pb-3 text-xs font-black ${active ? 'border-violet-600 text-violet-700' : 'border-transparent text-slate-500'}`}>{label}</button>;
const Kpi = ({ title, value }: { title: string; value: string }) => <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase text-slate-500">{title}</p><p className="mt-2 text-xl font-black text-slate-900">{value}</p></div>;
const Panel = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="mb-3 flex items-center gap-2 text-sm font-black text-slate-900"><BarChart3 className="h-4 w-4 text-violet-600" />{title}</h3>{children}</section>;
const Empty = ({ text }: { text: string }) => <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm font-semibold text-slate-500"><AlertTriangle className="mx-auto mb-2 h-5 w-5 text-amber-500" />{text}</div>;
const Input = ({ label, type, value, setValue }: { label: string; type: string; value: string; setValue: (value: string) => void }) => <label className="text-[10px] font-black uppercase text-slate-500">{label}<input type={type} value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-xs" /></label>;
const Select = ({ label, value, setValue, values }: { label: string; value: string; setValue: (value: string) => void; values: string[] }) => <label className="text-[10px] font-black uppercase text-slate-500">{label}<select value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-xs">{values.map((item) => <option key={item} value={item}>{item || 'Todos'}</option>)}</select></label>;
const CommercialChart = ({ data, line = false }: { data: Array<{ name: string; ventas: number }>; line?: boolean }) => data.length ? <div className="h-56"><ResponsiveContainer width="100%" height="100%">{line ? <LineChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="ventas" stroke="#7c3aed" strokeWidth={2} /></LineChart> : <BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="ventas" fill="#7c3aed" radius={[3, 3, 0, 0]} /></BarChart>}</ResponsiveContainer></div> : <Empty text="Sin datos verificables para este indicador." />;
const Table = ({ headers, rows }: { headers: string[]; rows: string[][] }) => rows.length ? <div className="max-h-80 overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-white text-[10px] uppercase text-slate-500"><tr>{headers.map((header) => <th key={header} className="border-b border-slate-200 px-2 py-2">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.join('|')}-${index}`} className="border-b border-slate-100">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-2 py-2 text-slate-700">{cell}</td>)}</tr>)}</tbody></table></div> : <Empty text="Sin registros válidos." />;
